if(CMAKE_HOST_SYSTEM_NAME MATCHES Linux)
	if(VERBOSE)
		execute_process(COMMAND tar -cvf ${CMAKE_BINARY_DIR}/initrd.img -C ${CMAKE_BINARY_DIR}/initrd .)
	else()
		execute_process(COMMAND tar -cf ${CMAKE_BINARY_DIR}/initrd.img -C ${CMAKE_BINARY_DIR}/initrd .)
	endif()
else()
	message(FATAL_ERROR "Unsupported host system: ${CMAKE_HOST_SYSTEM_NAME}")
endif()