# set(CMAKE_SYSTEM_NAME Mai-OS)
# set(CMAKE_SYSTEM_VERSION 0.0.1)
# set(CMAKE_SYSTEM_PROCESSOR x86_64)
# TODO Change this to Mai-OS

set(CMAKE_C_COMPILER ${CMAKE_CURRENT_LIST_DIR}/compiler/bin/x86_64-elf-gcc CACHE PATH "" FORCE)
set(CMAKE_CXX_COMPILER ${CMAKE_CURRENT_LIST_DIR}/compiler/bin/x86_64-elf-gcc CACHE PATH "" FORCE)
set(CMAKE_ASM_COMPILER /usr/bin/nasm)
set(CMAKE_LINKER ${CMAKE_CURRENT_LIST_DIR}/compiler/bin/x86_64-elf-gcc CACHE PATH "" FORCE)

set(CMAKE_C_COMPILER_WORKS true)
set(CMAKE_CXX_COMPILER_WORKS true)
set(CMAKE_ASM_COMPILER_WORKS true)
set(CMAKE_LINKER_WORKS true)